### ISSUE TITLE
Win Condition?

### ISSUE THREAD

**Issue by andibagandi** [ItsWasteD/Energy-Air-Bot#2]
Did someone already win? Does it automatically send a text message or is a user input required?
I'm not sure, but maybe you have to stop the page, after win. Like this:
    verloren = tree.xpath('//div[@id="content"]/h2/text()')
    if verloren[0] == "Glückwunsch!":
             user should interact

Thank you for your effort

**Comment by ItsWasteD** [comment]
First of all, yes a friend of me already won with an older version of the bot. If you win the bot is still running but it will not click the button. My friend told me it will send you an email but I don't know. But I'm pretty sure that no more user input is required. And even if one is required you will see the page because the bot will not click anything. I would add a win condition if I would now what the text exactly says if you win xD.

I should add that as you can read on the website of energy only 100 tickets can be won per day.
